src/Hammurabi/Models/Meal.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Hammurabi.Models
{
    public class Meal
    {
        public int ID { get; set; }

        [Display(Name = "Meal name:")]
        [Required(ErrorMessage = "You have to write meal name")]
        [StringLength(50)]
        public string Name { get; set; }

        [DataType(DataType.Currency)]
        [Required(ErrorMessage = "You have to write price")]
        public decimal Price { get; set; }

        [Display(Name = "Preparation Time:")]
        [Required(ErrorMessage = "You have to write preparation time")]
        public int PreparationTime { get; set; }

        public ICollection<MealIngredient> MealIngredients { get; set; }
    }
}

src/Hammurabi/Controllers/IngredientsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Hammurabi.Data;
using Hammurabi.Models;
using Microsoft.AspNetCore.Authorization;

namespace Hammurabi.Controllers
{
    public class IngredientsController : Controller
    {
        private readonly RestaurantContext _context;

        public IngredientsController(RestaurantContext context)
        {
            _context = context;    
        }

        // GET: Ingredients
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Index()
        {
            return View(await _context.Ingredients.ToListAsync());
        }


        // GET: Ingredients/Details/5
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var ingredient = await _context.Ingredients.SingleOrDefaultAsync(m => m.IngredientID == id);
            if (ingredient == null)
            {
                return NotFound();
            }

            return View(ingredient);
        }

        // GET: Ingredients/Create
        [Authorize(Roles = "Admin")]
        public IActionResult Create()
        {
            return View();
        }

        // POST: Ingredients/Create
        [Authorize(Roles = "Admin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("IngredientID,AddPrice,Name")] Ingredient ingredient)
        {
            if (ModelState.IsValid)
            {
                _context.Add(ingredient);
                await _context.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(ingredient);
        }

        // GET: Ingredients/Edit/5
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var ingredient = await _context.Ingredients.SingleOrDefaultAsync(m => m.IngredientID == id);
            if (ingredient == null)
            {
                return NotFound();
            }
            return View(ingredient);
        }

        // POST: Ingredients/Edit/5
        [Authorize(Roles = "Admin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("IngredientID,AddPrice,Name")] Ingredient ingredient)
        {
            if (id != ingredient.IngredientID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(ingredient);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!IngredientExists(ingredient.IngredientID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction("Index");
            }
            return View(ingredient);
        }

        // GET: Ingredients/Delete/5
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var ingredient = await _context.Ingredients.SingleOrDefaultAsync(m => m.IngredientID == id);
            if (ingredient == null)
            {
                return NotFound();
            }

            return View(ingredient);
        }

        // POST: Ingredients/Delete/5
        [Authorize(Roles = "Admin")]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var ingredient = await _context.Ingredients.SingleOrDefaultAsync(m => m.IngredientID == id);
            _context.Ingredients.Remove(ingredient);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        private bool IngredientExists(int id)
        {
            return _context.Ingredients.Any(e => e.IngredientID == id);
        }
    }
}

src/Hammurabi/Views/Meals/Create.cshtml
@model Hammurabi.Models.Meal

@{
    ViewData["Title"] = "Create";
}

<h2>Create</h2>

<form asp-action="Create">
    <div class="form-horizontal">
        <h4>Meal</h4>
        <hr />
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <div class="form-group">
            <label asp-for="Name" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger" />
            </div>
        </div>
        <div class="form-group">
            <label asp-for="PreparationTime" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="PreparationTime" class="form-control" />
                <span asp-validation-for="PreparationTime" class="text-danger" />
            </div>
        </div>
        <div class="form-group">
            <label asp-for="Price" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="Price" class="form-control" />
                <span asp-validation-for="Price" class="text-danger" />
            </div>
        </div>


        

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <table>
                    <tr>
                        @{
                            int cnt = 0;
                            List<Hammurabi.Models.RestaurantViewModels.AssignedIngredientData> ingredients = ViewBag.Ingredients;

                            foreach (var ingredient in ingredients)
                            {
                                if (cnt++ % 3 == 0)
                                {
                                    @:</tr><tr>
                                }
                                @: <td>
                                    <input type="checkbox"
                                           name="selectedIngredients"
                                           value="@ingredient.IngredientID" @*@*TO TUTAJ BYL PROBEM PODCZAS PRZEKAWYWANIA WARTOSI INPUTA DO KONTROLERA!*@*@
                                           @(Html.Raw(ingredient.Assigned ? "checked=\"checked\"" : "")) />
                                    @ingredient.IngredientID @:  @ingredient.Name
                                    @:</td>
                    }
                            @:</tr>
                        }
                    </table>
                </div>
            </div>




        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
</form>

<div>
    <a asp-action="EditMenu">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

src/Hammurabi/Views/Meals/Delete.cshtml
@model Hammurabi.Models.Meal

@{
    ViewData["Title"] = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Meal</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.PreparationTime)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.PreparationTime)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Price)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Price)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            <a asp-action="EditMenu">Back to List</a>
        </div>
    </form>
</div>

src/Hammurabi/Views/Meals/Details.cshtml
@model Hammurabi.Models.Meal

@{
    ViewData["Title"] = "Details";
}

<h2>Details</h2>

<div>
    <h4>Meal</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.PreparationTime)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.PreparationTime)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Price)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Price)
        </dd>

        <dt>
            @Html.DisplayName("Ingredient List:")
        </dt>
        <dd>
            <table class="table">
                <tr>
                    <th>List:</th>
                </tr>
                @*Code for display each item of Ingredient list for each Meal. Ingredients are order by IngredientID.*@
                @foreach (var item in Model.MealIngredients.OrderBy(a => a.IngredientID))
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.Ingredient.Name)
                        </td>
                    </tr>
                }
            </table>
        </dd>

    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.ID">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

src/Hammurabi/Views/Meals/Edit.cshtml
@model Hammurabi.Models.Meal

@{
    ViewData["Title"] = "Edit";
}

<h2>Edit</h2>

<form asp-action="Edit">
    <div class="form-horizontal">
        <h4>Meal</h4>
        <hr />
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <input type="hidden" asp-for="ID" />
        <div class="form-group">
            <label asp-for="Name" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger" />
            </div>
        </div>
        <div class="form-group">
            <label asp-for="PreparationTime" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="PreparationTime" class="form-control" />
                <span asp-validation-for="PreparationTime" class="text-danger" />
            </div>
        </div>
        <div class="form-group">
            <label asp-for="Price" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="Price" class="form-control" />
                <span asp-validation-for="Price" class="text-danger" />
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <table>
                    <tr>
                        @{
                            int cnt = 0;
                            List<Hammurabi.Models.RestaurantViewModels.AssignedIngredientData> ingredients = ViewBag.Ingredients;

                            foreach (var ingredient in ingredients)
                            {
                                if (cnt++ % 3 == 0)
                                {
                                    @:</tr><tr>
                                }
                                @:<td>
                                      <input type="checkbox"
                                             name="selectedIngredients"
                                             value="@ingredient.IngredientID" @*@*TO TUTAJ BYL PROBEM PODCZAS PRZEKAWYWANIA WARTOSI INPUTA DO KONTROLERA!*@*@
                                             @(Html.Raw(ingredient.Assigned ? "checked=\"checked\"" : "")) />
                                          @ingredient.IngredientID @:  @ingredient.Name
                                    @:</td>
                              }
                            @:</tr>
                        }
                    </table>
                </div>
            </div>



        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
</form>

<div>
    <a asp-action="EditMenu">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

src/Hammurabi/Views/Meals/EditMenu.cshtml
@model IEnumerable<Hammurabi.Models.Meal>

@{
    ViewData["Title"] = "IndexUser";
}
<style>
    body {
        @*Add background for this site - image - not necessary, i replace it by place this background in _layout shared cshtml file*@ @*background: url('@Url.Content("~/images/meal.jpg")');
        *@;
    }

    .table {
        @*Add background color(gray) and opacity 50% for table*@ background-color:rgba(194,194,194,0.5);
    }
</style>

<h2>Index</h2>

<p>

        <li><a asp-action="Create">Create new meal</a></li>
        <li><a asp-area="" asp-controller="Ingredients" asp-action="Index">Edit Ingredients</a></li>

</p>

<form asp-action="Index" method="get">
    <div class="form-actions no-color">
        <p>
            Find by name: <input type="text" name="SearchString" value="@ViewData["currentFilter"]" />
            <input type="submit" value="Search" class="btn btn-default" /> |
            <a asp-action="EditMenu">Back to List</a>
        </p>
    </div>
</form>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @*@Html.DisplayNameFor(model => model.MealIngredients)*@
                @Html.DisplayName("Ingredients List:")
            </th>
            <th>
                <a asp-action="EditMenu" asp-route-sortOrder="@ViewBag.TimeSortParm">@Html.DisplayNameFor(model => model.PreparationTime) (min)</a>
                @*@Html.DisplayNameFor(model => model.PreparationTime)*@
            </th>
            <th>
                <a asp-action="EditMenu" asp-route-sortOrder="@ViewBag.PriceSortParm">@Html.DisplayNameFor(model => model.Price) ($)</a>
                @*@Html.DisplayNameFor(model => model.Price)*@
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    <table class="table2">
                        @*Code for display each item of Ingredient list for each Meal. Ingredients are order by IngredientID.*@
                        @foreach (var item2 in item.MealIngredients.OrderBy(a => a.IngredientID))
                        {
                            <tr>
                                <td>
                                    @Html.DisplayFor(modelItem => item2.Ingredient.Name)
                                </td>
                            </tr>
                        }
                    </table>
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.PreparationTime)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Price)
                </td>
                <td>
                    <a asp-action="Edit" asp-route-id="@item.ID">Edit</a> |
                    <a asp-action="Details" asp-route-id="@item.ID">Details</a> |
                    <a asp-action="Delete" asp-route-id="@item.ID">Delete</a>
                </td>
            </tr>
        }
    </tbody>
</table>

src/Hammurabi/Views/Meals/Index.cshtml
@*@model IEnumerable<Hammurabi.Models.Meal>*@
@model PaginatedList<Hammurabi.Models.Meal>

@{
    ViewData["Title"] = "Index";
}
<style>
    body {
        @*Add background for this site - image - not necessary, i replace it by place this background in _layout shared cshtml file*@ 
        @*background: url('@Url.Content("~/images/meal.jpg")'); *@;
    }
    .table{
      @*Add background color(gray) and opacity 50% for table*@
      background-color:rgba(194,194,194,0.5);    
    }
</style>

<h2>Index</h2>


<form asp-action="Index" method="get">
    <div class="form-actions no-color">
        <p>
            Find by name: <input type="text" name="SearchString" value="@ViewData["currentFilter"]" />
            <input type="submit" value="Search" class="btn btn-default" /> |
            <a asp-action="Index">Back to List</a>
        </p>
    </div>
</form>

<table class="table">
    <thead>
        <tr>
            <th>
                @*@Html.DisplayNameFor(model => model.Name)*@
                Name
            </th>
            <th>
                @*@Html.DisplayNameFor(model => model.MealIngredients)*@
                @Html.DisplayName("Ingredients List:")
            </th>
            <th>
                @*version without paging functionality*@
                @*<a asp-action="Index" asp-route-sortOrder="@ViewBag.TimeSortParm">@Html.DisplayNameFor(model => model.PreparationTime) (min)</a>*@

                @*version with paging functionality*@
                <a asp-action="Index" asp-route-sortOrder="@ViewData["TimeSortParm"]" asp-route-currentFilter="@ViewData["CurrentFilter"]">Preparation Time</a>
                @*@Html.DisplayNameFor(model => model.PreparationTime)*@
            </th>
            <th>
                @*version without paging functionality*@
                @*<a asp-action="Index" asp-route-sortOrder="@ViewBag.PriceSortParm">@Html.DisplayNameFor(model => model.Price) ($)</a>*@

                @*version with paging functionality*@
                <a asp-action="Index" asp-route-sortOrder="@ViewData["PriceSortParm"]" asp-route-currentFilter="@ViewData["CurrentFilter"]">Price</a>
                @*@Html.DisplayNameFor(model => model.Price)*@
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                <table class="table2">
                    @*Code for display each item of Ingredient list for each Meal. Ingredients are order by IngredientID.*@
                    @foreach (var item2 in item.MealIngredients.OrderBy(a => a.IngredientID))
                         {
                            <tr>
                                <td>
                                    @Html.DisplayFor( modelItem => item2.Ingredient.Name)
                                </td>
                            </tr>
                        }
                </table>
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PreparationTime)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Price)
            </td>
            <td>
                <a asp-action="Details" asp-route-id="@item.ID">Details</a> |
            </td>
        </tr>
}
    </tbody>
</table>

@*added for paging functionality*@
@{
    var prevDisabled = !Model.HasPreviousPage ? "disabled" : "";
    var nextDisabled = !Model.HasNextPage ? "disabled" : "";
}

<a asp-action="Index"
   asp-route-sortOrder="@ViewData["CurrentSort"]"
   asp-route-page="@(Model.PageIndex - 1)"
   asp-route-currentFilter="@ViewData["CurrentFilter"]"
   class="btn btn-default @prevDisabled btn">
    Previous
</a>
<a asp-action="Index"
   asp-route-sortOrder="@ViewData["CurrentSort"]"
   asp-route-page="@(Model.PageIndex + 1)"
   asp-route-currentFilter="@ViewData["CurrentFilter"]"
   class="btn btn-default @nextDisabled btn">
    Next
</a>